FROM registry.cn-hangzhou.aliyuncs.com/carfield-centos/centos7:7
  
MAINTAINER wangxin "wangxin0072000@gmail.com"  
  
  
# Install curl,gcc,cmake
RUN yum update -y
RUN yum -y install curl
RUN yum -y install gcc-c++-4.8.5-16.el7
RUN yum -y install cmake
gcc --version
g++ --version
uname -a
  
